platform :ios, '9.0'
use_frameworks!

target 'MosaicLayout' do
    pod 'AFNetworking', '~> 2.6'
    pod 'ORStackView', '~> 3.0'
    pod 'SwiftyJSON', '~> 2.3'
    pod 'C4'
    pod "FMMosaicLayout"
end

